//
// repo:            progs_invest
// file:			export_symbols.h
// path:			include/progs_invest/export_symbols.h
// created on:		2023 Mar 08
// created by:		Davit Kalantaryan (davit.kalantaryan@desy.de)
//

#ifndef PROGS_INVEST_INCLUDE_PROGS_INVEST_EXPORT_SYMBOLS_H
#define PROGS_INVEST_INCLUDE_PROGS_INVEST_EXPORT_SYMBOLS_H

#include <progs_invest/internal_header.h>


#ifndef PROGSINVEST_ALLOCFREEHOOK_EXPORT
#if defined(PROGSINVEST_ALLOCFREEHOOK_COMPILING_SHARED_LIB)
#define PROGSINVEST_ALLOCFREEHOOK_EXPORT CPPUTILS_DLL_PUBLIC
#elif defined(PROGSINVEST_ALLOCFREEHOOK_USING_STATIC_LIB_OR_OBJECTS)
#define PROGSINVEST_ALLOCFREEHOOK_EXPORT
#elif defined(PROGSINVEST_ALLOCFREEHOOK_LOAD_FROM_DLL)
#define PROGSINVEST_ALLOCFREEHOOK_EXPORT CPPUTILS_IMPORT_FROM_DLL
#else
#define PROGSINVEST_ALLOCFREEHOOK_EXPORT CPPUTILS_DLL_PRIVATE
#endif
#endif


#ifndef PROGSINVEST_STACKCALCS_EXPORT
#if defined(PROGSINVEST_STACKCALCS_COMPILING_SHARED_LIB)
#define PROGSINVEST_STACKCALCS_EXPORT CPPUTILS_DLL_PUBLIC
#elif defined(PROGSINVEST_STACKCALCS_USING_STATIC_LIB_OR_OBJECTS)
#define PROGSINVEST_STACKCALCS_EXPORT
#elif defined(PROGSINVEST_STACKCALCS_LOAD_FROM_DLL)
#define PROGSINVEST_STACKCALCS_EXPORT CPPUTILS_IMPORT_FROM_DLL
#else
#define PROGSINVEST_STACKCALCS_EXPORT CPPUTILS_DLL_PRIVATE
#endif
#endif


#ifndef PROGSINVEST_MEMLEAKINVEST_EXPORT
#if defined(PROGSINVEST_MEMLEAKINVEST_COMPILING_SHARED_LIB)
#define PROGSINVEST_MEMLEAKINVEST_EXPORT CPPUTILS_DLL_PUBLIC
#elif defined(PROGSINVEST_MEMLEAKINVEST_USING_STATIC_LIB_OR_OBJECTS)
#define PROGSINVEST_MEMLEAKINVEST_EXPORT
#elif defined(PROGSINVEST_MEMLEAKINVEST_LOAD_FROM_DLL)
#define PROGSINVEST_MEMLEAKINVEST_EXPORT CPPUTILS_IMPORT_FROM_DLL
#else
#define PROGSINVEST_MEMLEAKINVEST_EXPORT CPPUTILS_DLL_PRIVATE
#endif
#endif


#endif  // #ifndef PROGS_INVEST_INCLUDE_PROGS_INVEST_EXPORT_SYMBOLS_H
